### ISSUE TITLE
Integrate checkpoint system with UI

### ISSUE THREAD

**Issue by chbroecker** [thoklei/amazing_maze#17]
- [x] fix checkpoint system
- [x] merge that into the ui branch
- [x] connect the checkpoints with the UI
- [x] merge into dev

**Comment by TilmanKalthoff** [comment]
coincounter for each door:
level 1: 20 (display x/20)
level 2: -
level 3: 25 (display x/5)
level 4: 35 (display x/10)
level 5: 50 (display x/15)
level 6: tbd

**Comment by chbroecker** [comment]
Things to do when adding a checkpoint:

1. Create the Box of the Checkpoint
2. Add a mesh collider
3. Check the "is trigger" box on the mesh collider component
4. Add Checkpoint Script
5. drag in the image component from the corresponding CheckpointUI to the SerializableField 
6. add the checkpoint that was created here to the CheckpointManager
