### ISSUE TITLE
Sound

### ISSUE THREAD

**Issue by chbroecker** [thoklei/amazing_maze#2]
- [x] soundmanager aus dem wurmz game mopsen
- [x] roll sound (can we loop this?)
- [x] KLONK sound for when the ball hits a wall
- [x] windrad
- [x] canons
- [x] sliding sound for door
- [x] pling sound for button
- [x] coin sound

- [x] ghost weapon sound
- [ ]

**Comment by TilmanKalthoff** [comment]
roll sound maybe obsolete? KLONK might be enough for "immersion"
