### ISSUE TITLE
Display the relevant needed coin amount in the UI for each level

### ISSUE THREAD

**Issue by chbroecker** [thoklei/amazing_maze#22]
coincounter for each door:
level 1: 20 (display x/20)
level 2: -
level 3: 25 (display x/5)
level 4: 35 (display x/10)
level 5: 50 (display x/15)
level 6: tbd

_Originally posted by @TilmanKalthoff in https://github.com/thoklei/amazing_maze/issues/17#issuecomment-924056963_

**Comment by LDankert** [comment]
#34 adds this feature
